name: task_manager
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.2
  percent_indicator: ^4.0.1
  dotted_border: ^2.0.0+3
  msh_checkbox: ^2.0.1
  firebase_core:
  firebase_auth:
  firebase_database:
  fluttertoast: ^8.2.2
  easy_loading_button: ^0.3.2
  rounded_loading_button: ^2.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
   - assets/