// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1mYHmvK0lvEZrhYRbhX-Aiyl6pOdMLL0',
    appId: '1:223095615588:android:5e906c18ff2b9b9355ef71',
    messagingSenderId: '223095615588',
    projectId: 'task-manager-778f9',
    storageBucket: 'task-manager-778f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4g87h9h2OetLO3SQKZGNRmOF6sDfWE3k',
    appId: '1:223095615588:ios:88cde5e15a70c49055ef71',
    messagingSenderId: '223095615588',
    projectId: 'task-manager-778f9',
    storageBucket: 'task-manager-778f9.appspot.com',
    iosClientId: '223095615588-7bb3dct42hnujhuihq8922qii43a3han.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );
}
